### ISSUE TITLE
Optimize customTransferList

### ISSUE THREAD

**Issue by RetroMeras** [dsomni/accept_front#66]
Poor performance on pages with customTransferList.
Maybe do not draw items with is not in viewport

**Comment by RetroMeras** [comment]
@dsomni

**Comment by dsomni** [comment]
Virtual scroll works now 2e6983ae1e45e68f6728c96422f9b0eeb0fc5c62

However, it should be rewritten, as the following issues still present:

- [ ] Rernder all the component after selecting the item
- [ ] Search disappears after selecting the item
- [ ] Should scroll to the previous position after selecting the item
